#@file
# Contains the mappings for fields in Fedora => Spotlight

---
headers: &headers
  full_title_field:
    ds: DCA-META
    element: { field: "title" }

  full_image: Advanced.jpg
  thumb: Thumbnail.png

streams: &streams
  streams:
    DCA-META:
      elems:
        # facet = show in facets -- results = show in index view
        - { field: creator, facet: true, results: true }
        - { field: description, results: true }
        - { field: publisher, facet: true, results: true }
        - { field: temporal, name: Date, facet: true, results: true }
        - { field: created, name: "Date Created" }
        - { field: subject, facet: true }
        - { field: type, facet: true, results: true }
        - { field: format, facet: true }
        - { field: rights }
        - { field: corpname, name: Corporation, facet: true }
        - { field: geogname, name: "Area of Interest", facet: true }
        - { field: bibliographicCitation, name: Citation }
        - { field: identifier, name: "Permanent URL" }

development:
  << : *headers
  << : *streams
tdldev:
  << : *headers
  << : *streams
test:
  << : *headers
  streams:
    DCA-META:
      elems:
        - { field: description, results: true}
        - { field: creator, results: true, facet: true  }
        - { field: source }
        - { field: publisher, name: published_by }
        - { field: subject, facet: true }
    RELS-EXT:
      elems:
        - { field: "/RDF/Description/isMemberOfCollection/@resource", name: member_of }
production:
  << : *headers
  << : *streams

